run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - errorlint
    - unconvert
    - unparam
    - nolintlint
    - copyloopvar

issues:
  exclude-dirs:
    - gen
