version: '2'
linters:
  enable:
    - copyloopvar
    - errorlint
    - gocritic
    - misspell
    - nolintlint
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - gen
      - frontend
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - gen
      - frontend
      - third_party$
      - builtin$
      - examples$
