global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: server
    static_configs:
      - targets: ['server:8080', 'server-shard-1:8080']

  - job_name: geofence
    static_configs:
      - targets: ['geofence:8081', 'geofence-shard-1:8081']
