global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: server
    static_configs:
      - targets: ['server:8080']

  - job_name: geofence
    static_configs:
      - targets: ['geofence:8081', 'geofence-shard-1:8081']
